### ISSUE TITLE
Module Multilanguage

### ISSUE THREAD

**Issue by vades** [vades/zwave-smarthome#14]
please install v2.0.1-rc11a. Here we have now mutlilanguage support in Modules
[02.02.15 17:30:48] Poltorak Serguei: http://localhost:8083/ZAutomation/api/v1/modules/Camera
[02.02.15 17:30:49] Poltorak Serguei: http://localhost:8083/ZAutomation/api/v1/modules/Camera?lang=ru
or better put lang=ru in header

The camera module has a directory /lang in /automation/modules/Camera. there you find the translations
Please work with Niels on translating the most important Modules, first his modules but also
Weather and Z-Wave Binding. I will work on the other modules if I have time.

**Comment by PoltoS** [comment]
Please push to https://github.com/Z-Wave-Me/home-automation/tree/develop your translations. We will also work on RU translations, so push immediately after you have added language file not to merge them with our changes. @aivs will work on this on our side.

You can translate label and helper fields (may be some other too - check the code).
